version: "3.2"
services:
  zookeeper:
    image: "bitnami/zookeeper:3.6.1"
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes: 
      - ./zookeeper/data:/zookeeper/data
      - ./zookeeper/datalog:/zookeeper/datalog
  kafka:
    image: "bitnami/kafka:2.5.0"
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes: 
      - ./kafka/data:/kafka/data
    depends_on:
      - zookeeper
